/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assets
         * @description Supported coins.
         */
        get: operations["list_assets_v1_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candles
         * @description Closed candles (oldest first) with indicator series computed on the server.
         */
        get: operations["get_candles_v1_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description When each job last succeeded and how fresh the stored candles are.
         */
        get: operations["get_status_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predictions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Prediction
         * @description The current signal for one coin and timeframe, with its reasons and live track record.
         */
        get: operations["latest_prediction_v1_predictions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/predictions/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prediction History
         * @description Past signals, newest first, with what actually happened.
         */
        get: operations["prediction_history_v1_predictions_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Markets
         * @description Every coin with its last price, 24h change and the latest signal per timeframe.
         */
        get: operations["markets_v1_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track Record
         * @description Live track record: model accuracy next to the baselines, always (docs/06).
         */
        get: operations["track_record_v1_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/performance/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track Record Summary
         * @description Live track record for every active coin and timeframe, plus the overall numbers.
         */
        get: operations["track_record_summary_v1_performance_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_v1_watchlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/watchlist/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Watchlist */
        put: operations["put_watchlist_v1_watchlist__symbol__put"];
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_v1_watchlist__symbol__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus a database check. Railway calls this to decide if the service is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetOut */
        AssetOut: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Exchange Symbol */
            exchange_symbol: string;
        };
        /** CandleFreshness */
        CandleFreshness: {
            /** Timeframe */
            timeframe: string;
            /** Latest Open Time */
            latest_open_time: string | null;
            /** Stale */
            stale: boolean;
        };
        /** CandleOut */
        CandleOut: {
            /**
             * T
             * Format: date-time
             */
            t: string;
            /** O */
            o: string;
            /** H */
            h: string;
            /** L */
            l: string;
            /** C */
            c: string;
            /** V */
            v: string;
            /** Ema9 */
            ema9: number | null;
            /** Ema21 */
            ema21: number | null;
            /** Ema50 */
            ema50: number | null;
            /** Bb Upper */
            bb_upper: number | null;
            /** Bb Mid */
            bb_mid: number | null;
            /** Bb Lower */
            bb_lower: number | null;
            /** Rsi14 */
            rsi14: number | null;
            /** Macd */
            macd: number | null;
            /** Macd Signal */
            macd_signal: number | null;
            /** Macd Hist */
            macd_hist: number | null;
        };
        /** CandlesResponse */
        CandlesResponse: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Candles */
            candles: components["schemas"]["CandleOut"][];
            /** Stale */
            stale: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Label */
            label: string;
            /** P Up */
            p_up: number;
            /**
             * Base Open Time
             * Format: date-time
             */
            base_open_time: string;
            /**
             * Target Open Time
             * Format: date-time
             */
            target_open_time: string;
            /** Base Close */
            base_close: string;
            /** Model Status */
            model_status: string;
            outcome: components["schemas"]["OutcomeOut"] | null;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Items */
            items: components["schemas"]["HistoryItem"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Job Name */
            job_name: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /** LabelStats */
        LabelStats: {
            /** N */
            n: number;
            /** Accuracy */
            accuracy: number | null;
        };
        /** MarketRow */
        MarketRow: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Last Price */
            last_price: string | null;
            /** Change 24H Pct */
            change_24h_pct: number | null;
            /** Signals */
            signals: {
                [key: string]: components["schemas"]["SignalChip"] | null;
            };
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: number;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /** Status */
            status: string;
        };
        /** ModelStatus */
        ModelStatus: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Model Version Id */
            model_version_id: number;
            /**
             * Trained At
             * Format: date-time
             */
            trained_at: string;
            /** Status */
            status: string;
        };
        /** OutcomeOut */
        OutcomeOut: {
            /** Target Close */
            target_close: string;
            /** Actual Direction */
            actual_direction: string;
            /** Correct */
            correct: boolean | null;
            /** Return Pct */
            return_pct: number;
        };
        /** PerformanceBaseline */
        PerformanceBaseline: {
            /** Naive */
            naive: number | null;
            /** Always Up */
            always_up: number | null;
        };
        /** PerformanceOut */
        PerformanceOut: {
            /** Symbol */
            symbol: string | null;
            /** Timeframe */
            timeframe: string | null;
            /** Days */
            days: number;
            /** N Predictions */
            n_predictions: number;
            /** N Resolved */
            n_resolved: number;
            /** Coverage */
            coverage: number | null;
            /** Accuracy */
            accuracy: number | null;
            baseline: components["schemas"]["PerformanceBaseline"];
            /** Brier */
            brier: number | null;
            /** Brier Baseline */
            brier_baseline: number | null;
            /** By Label */
            by_label: {
                [key: string]: components["schemas"]["LabelStats"];
            };
            /** Low Sample */
            low_sample: boolean;
        };
        /**
         * PerformanceSummary
         * @description Every coin x timeframe in one response (the track-record page makes one request).
         */
        PerformanceSummary: {
            /** Days */
            days: number;
            overall: components["schemas"]["PerformanceOut"];
            /** Rows */
            rows: components["schemas"]["PerformanceOut"][];
        };
        /** PredictionOut */
        PredictionOut: {
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Label */
            label: string;
            /** P Up */
            p_up: number;
            /**
             * Base Open Time
             * Format: date-time
             */
            base_open_time: string;
            /**
             * Target Open Time
             * Format: date-time
             */
            target_open_time: string;
            /**
             * Target Close Time
             * Format: date-time
             */
            target_close_time: string;
            /** Base Close */
            base_close: string;
            /** Reasons */
            reasons: components["schemas"]["ReasonOut"][];
            /** Sentiment Agg */
            sentiment_agg: number;
            model: components["schemas"]["ModelInfo"];
            recent_accuracy: components["schemas"]["RecentAccuracy"];
            /**
             * Disclaimer
             * @default Signals are probabilistic estimates for information and education only, not financial advice. Crypto is volatile and you can lose all the money you invest. Past performance does not guarantee future results. TradeMatrix AI does not execute trades.
             */
            disclaimer: string;
            /** Stale */
            stale: boolean;
        };
        /** ReasonOut */
        ReasonOut: {
            /** Code */
            code: string;
            /** Text */
            text: string;
            /** Effect */
            effect: string;
        };
        /**
         * RecentAccuracy
         * @description Live track record of this coin and timeframe (last 200 resolved predictions).
         */
        RecentAccuracy: {
            /** Model */
            model: number | null;
            /** Naive Baseline */
            naive_baseline: number | null;
            /** N */
            n: number;
            /** Low Sample */
            low_sample: boolean;
        };
        /** SignalChip */
        SignalChip: {
            /** Label */
            label: string;
            /** P Up */
            p_up: number;
            /**
             * Target Open Time
             * Format: date-time
             */
            target_open_time: string;
            /** Model Status */
            model_status: string;
            /** Stale */
            stale: boolean;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Candles */
            candles: components["schemas"]["CandleFreshness"][];
            /** Models */
            models: components["schemas"]["ModelStatus"][];
            /** Stale */
            stale: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /** Symbols */
            symbols: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assets_v1_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
        };
    };
    get_candles_v1_candles_get: {
        parameters: {
            query: {
                symbol: string;
                tf: "1h" | "4h" | "1d";
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    latest_prediction_v1_predictions_latest_get: {
        parameters: {
            query: {
                symbol: string;
                tf: "1h" | "4h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prediction_history_v1_predictions_history_get: {
        parameters: {
            query: {
                symbol: string;
                tf: "1h" | "4h" | "1d";
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markets_v1_markets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketRow"][];
                };
            };
        };
    };
    track_record_v1_performance_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                tf?: ("1h" | "4h" | "1d") | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_record_summary_v1_performance_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_v1_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
        };
    };
    put_watchlist_v1_watchlist__symbol__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_v1_watchlist__symbol__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
